### ISSUE TITLE
strict priority queues in P4 14 code 

### ISSUE THREAD

**Issue by ColdsteelRail** [nsg-ethz/SP-PIFO#2]
Excited to run sp-pifo testbed code, here I have a question.
In the p4-14 Tofino code, strict priority queues are presented/mapped to the ig_intr_md_for_tm.qid filed.
However, I can't find any available Tofino documents showing that the ingress queues work in strict priority style.
So I'm wondering does the Tofino P4 code really run in strict priority queues style?
Thanks a lot !!!

**Comment by albertgran** [comment]
Hi @ColdsteelRail , 

Thank you so much for reaching out :)  

Indeed, one needs to first configure Tofino to use priority queues, such that the metadata instructions can be executed. 
Here is a code example on how to do so by using `pd_rpc`: 

    #General settings
    a_dev = 0
    a_port_0 = 136
    a_port_1 = 137

    #Queue identifiers
    a_queue0 = 0
    a_queue1 = 1
    a_queue2 = 2
    a_queue3 = 3
    a_queue4 = 4
    a_queue5 = 5
    a_queue6 = 6
    a_queue7 = 7

    #Obtaining and printing the default configuration of port 136
    a_mapping_default_0 = tm.thrift.tm_get_port_q_mapping(a_dev, a_port_0)
    a_mapping_default_1 = tm.thrift.tm_get_port_q_mapping(a_dev, a_port_1)
    print 'Default configuration:'
    print a_mapping_default_0

    #Settings for port 136: No queues allocated
    a_qmap_0 = tm.q_map_t(0)
    a_numqueues_0 = 0

    tm.thrift.tm_set_port_q_mapping(a_dev, a_port_0, a_numqueues_0, a_qmap_0)

    #Settings for port 137: 8 queues allocated, strict priority with 8 the highest priority
    a_qmap_1 = tm.q_map_t(0,1,2,3,4,5,6,7)
    a_numqueues_1 = 8

    tm.thrift.tm_set_port_q_mapping(a_dev, a_port_1, a_numqueues_1, a_qmap_1)

    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue0, 0)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue1, 1)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue2, 2)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue3, 3)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue4, 4)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue5, 5)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue6, 6)
    tm.thrift.tm_set_q_sched_priority(a_dev, a_port_1, a_queue7, 7)

    print 'Updated configuration:'
    a_mapping_new_0 = tm.thrift.tm_get_port_q_mapping(a_dev,a_port_0);
    a_mapping_new_1 = tm.thrift.tm_get_port_q_mapping(a_dev,a_port_1);
    print a_mapping_new_0
    print a_mapping_new_1
    
You can find another example of priority-queue configuration in Tofino here: 
https://github.com/nsg-ethz/ACC-Turbo/blob/main/tofino/pd_rpc/priority_queueing.py

All the best,
Albert
